### ISSUE TITLE
Unable to use pip?

### ISSUE THREAD

**Issue by hlambrinoudis** [cisc3620/review#10]
I have been having trouble getting python to use or upgrade pip for Windows. Whenever I type in:

python -m pip install -U pip setuptools 

I get the following:

  File "<stdin>", line 1
    python -m pip install -U pip setuptools
                ^
SyntaxError: invalid syntax

What should I do?

**Comment by rivlev** [comment]
are you typing this at the command prompt?

**Comment by hlambrinoudis** [comment]
I tried typing it in the command prompt at first and got this:

'python' is not recognized as an internal or external command,
operable program or batch file.

**Comment by TS96** [comment]
@hlambrinoudis you need to add python to your path. Assuming that you're on Windows 10, open the control panel, system and security, system, advanced system settings, then under the advanced tab open environmental variables and add it there. If you're on a different OS then just google it, the process will be pretty similar.

**Comment by hlambrinoudis** [comment]
@TS96  Thank you that seems to have fixed it.
