### ISSUE TITLE
Right handed order

### ISSUE THREAD

**Issue by J-A16** [cisc3620/review#11]
When crossing the w, -gaze, and up vectors to get the right vector, u, which vector is first in the crossing?

**Comment by J-A16** [comment]
@rivlev ?

**Comment by rivlev** [comment]
u = up x w
v = w x u

make an L with your thumb and forefinger as we showed in class, your middle finger is the positive z axis (w). If you point u (thumb) towards you, up x w is counter-clockwise direction. If you point v (forefinger) towards you, w (middle) x u (thumb) is ccw.

**Comment by rivlev** [comment]
Please close if this resolves your issue.
