### ISSUE TITLE
Need Help with Light problems

### ISSUE THREAD

**Issue by Mohamed-Alguhiem** [cisc3620/review#12]
Point p has a surface color of (0.0 1.0 0.5) and a surface normal of (0.22 0.44 0.87) Given a light of color (1.0 0.0 1.0) and direction (0.48 0.77 0.42), what will be the diffuse component of p's nal color?

so for this problem, I guess we need this formula.
c = crcl max(0; n.l)
1)  is n.l   mean  n*1 which is cross product or n.l which is dot product?

I know I have surface color, surface normal, light color, direction.
2)  How do I setup the problem
cr=?
cl=? 
n=?
l=?

3) And the main problem is how to solve MAX????

Thanks.
@rivlev

**Comment by rivlev** [comment]
1) dot in the middle is the dot product. cross product is denoted by x
2) cr is the surface color, cl is the light color, n is the normal, l is the light direction
3) max is just which is bigger. 0 if the dot product is negative, otherwise the dot product.

**Comment by rivlev** [comment]
Please close if this answers your question.

**Comment by Mohamed-Alguhiem** [comment]
ok thanks.
