### ISSUE TITLE
Question about camera transformation matrix calculation

### ISSUE THREAD

**Issue by JessiicaWu** [cisc3620/review#13]
From viewing review question 2:
Given a camera position of [3,3,4], a gaze vector of [2 -1 0], and an up vector of [-4, 3, 0], what is the resulting camera transformation matrix?

So what I understand is we take normalized the -w(gaze) vector. And for u = up x w, v = w x u. But I'm not too sure how to do this, I have a wrong outcome when I do this question. Thank you.

@rivlev

**Comment by Mohamed-Alguhiem** [comment]
STEP 1: SOLVE for W.
to solve for W you have to normalize the gaze vector
for example if your gaze is < 1  2  3 >

HOW TO NORMALIZE:
to normalize you have to do this squareroot(1^2  +  2^2  + 3^2)  then lets say your result was 0.1
then you will have to divide it by every element in the gaze vector
(1/0.1)  (2/0.1)  (3/0.1)
Now you have to negate the gaze vector. what ever result you get from those 3 divisions multiply by -1 or put the opposite direction. 

END OF SOLVING FOR W
____________________________________________

START OF SOLVING FOR U

To solve for U you need to first take the Cross product of the Up vector  and W 
This video will show you how to calculate the cross product of 2 vectors. https://www.youtube.com/watch?v=qsgK1d-_8ik

After you get your crossed vector of UP and W. now you need to normalize it. follow the previous normalized steps.

Note: YOU DO NOT NEGATE THIS ONE.

END OF SOLVING FOR U

____________________________________________
START OF SOLVING FOR V

V is the normalized Cross product of U and W.

STEP 1: take the cross product of U and W
STEP 2: Normalize the result from step 1

END OF SOLVING FOR U
____________________________________________

FINAL ANSWER:

NOW YOU HAVE 3 VECTORS    U   V   W

Just plug everything into this matrix

Ux   Uy   Uz    Px
Vx   Vy    Vz    Py
Wx   Wy  Wz   Pz
0       0      0    1

Note: If your W= <1  2  3>     U= <4  5  6>       V= <7  8  9>  Then your matrix should be:
4       5      6        3
7       8      9        3
1        2      3        4
0       0      0         1
Note: Your Px   Py   Pz are your camera position vector.

It is very easy to make mistake so watch your algebra carefully to get the correct answer.

**Comment by JessiicaWu** [comment]
Hi, I believe v = w x u, and I think order matters.

**Comment by Mohamed-Alguhiem** [comment]
I did UxW and I got correct answer. I think order matter so try UxW

**Comment by JessiicaWu** [comment]
Hmmm well I tried a different problem, my answer is still not the one she gave. So I'm not sure what did I do wrong.

**Comment by Mohamed-Alguhiem** [comment]
Which one did you try? I will try to solve it then send you a picture. Let me know your e-mail.

**Comment by JessiicaWu** [comment]
#23 on viewing review email: jessiicawu@gmail.com

**Comment by JessiicaWu** [comment]
Hi, I think I just forgot to normalize my u and v =) thanks for the help.

**Comment by Mohamed-Alguhiem** [comment]
so did you get the correct answer after normalizing?

**Comment by JessiicaWu** [comment]
Yes I did!! Thank you.

**Comment by Mohamed-Alguhiem** [comment]
Do you know the steps on solving question 7 on viewing review?
