### ISSUE TITLE
I Need Help With Question 4 on Lightening Review

### ISSUE THREAD

**Issue by Mohamed-Alguhiem** [cisc3620/review#14]
In this question, I am bein given too much information.

_______________________________ _______________________________ _______________________________
Surface Color = [ 1   1  1.5 ]                               ** I think this is the Cr **
Surface normal = [ 0.55  0.2  0.81 ]                  ** I think this is the n **
direction =[ 0.5  0.84  0.21 ]                              ** I think this is the l **
ambient color= [ 4  1  2 ]                                   ** I think this is the Ca **
view direction = [ 0.22  0.7  0.68 ]                   ** I have no idea what is this **
light color = [4  2  1]                                          ** I think this is the Cl **
phong exponent = 2                                         ** I think this is the e **
_______________________________ _______________________________ _______________________________

Now the problem is: I couldn't find a formula in the slides that will take all these 6 pieces of information to it.

Can you please tell me how to approach this problem, what formula to use for this problem and how to set it up?

Also, this is a different question. when should I use this formula  2N(R1 * N)  -􀀀 R1

Thanks.

@rivlev

**Comment by Mohamed-Alguhiem** [comment]
If This is the correct solution:
Final color will be ambient color + diffuse color + specular highlights

Diffuse color: I solved for it.
Ambient color: Given in the question (or do I have to solve for it)
Specular Highlights: I have a problem trying to figure out what is what !!! I found the formula: [Cl Max(0,e.r) ^p] 
so what is my e and r and p


Thanks 
@rivlev

**Comment by rivlev** [comment]
N is the normal
RI is the lighting direction
the reflected vector 2N (RI . N) - Rl will be unit length because the original lighting direction is unit length.

Ambient color is ca * cr

**Comment by Mohamed-Alguhiem** [comment]
but you provided ambient color in the question. Do I still have to calculate it?
also is RL one unit or two units like R and L

**Comment by rivlev** [comment]
ambient color is the color of the "fake" light
like cl is the color of the "real" light
so it gets multiplied with the surface color to produce the ambient component.

RL is one unit representing the ray (vector) in the lighting direction

**Comment by Mohamed-Alguhiem** [comment]
but in the question you gave us values for the ambient color. Do i take those values to be my ambient color or do i have to recalculate it for myself.

**Comment by rivlev** [comment]
The ambient color is different from the ambient component of the final color.
You use the ambient color to calculate the ambient component of the final color, which is ca (the ambient color) * cr (the surface color).

**Comment by Mohamed-Alguhiem** [comment]
Thanks.
