### ISSUE TITLE
Problem With Transformation Review

### ISSUE THREAD

**Issue by DenisBarabanov** [cisc3620/review#15]
Hey guys, anyone got a better explanation on transformation. I dont understand few things in the slides and i keep getting c++ and Matlab trash. From slides, there are very few explanations, most of the slides just show proofs or work, not how to implement it. 
where do i go from here...
x cos φ − y sin φ
x sin φ + y cos φ
z
1
From her review answers, when i try to apply the formula i do not get the same results.
i keep seeing

3

1

4

1

I dont understand where that came from...just appeared...

**Comment by Mohamed-Alguhiem** [comment]
which problem are you trying to solve? Pick a problem from the review and I will explain it to you.

**Comment by DenisBarabanov** [comment]
Create a matrix to rotate a point 0.44 radians around the z-axis.

**Comment by DenisBarabanov** [comment]
i can find like a YT or site link to explain all of the rotations, they keep giving me matlab

**Comment by DenisBarabanov** [comment]
Create a matrix to scale a point 3.75 along the x-axis and 4.10 along the y-axis and 4.08 along the

z-axis.

i have
3.75  0      0      0
0      4.10  0      0
0      0               4.08 0
0      0       0      1
then what... where is the 3 1 4 1 comes in....

**Comment by DenisBarabanov** [comment]
please no proofs and crap like that....i see that on every site, just want to know what to do...

**Comment by Mohamed-Alguhiem** [comment]
This is easy: 

1) You need a calculator and you need to make sure it is on radian mode.
2) You need to memorize the identity matrix for rotation.

Solving:

Step 1: get the Cosine of 0.44 in radians = 0.9999 
Step 2: get the Sin of 0.44 in radians  = 0.00767

Now plug these values into the identity Matrix:

The identity matrix is:

Cos theta  - Sine theta  0  0
Sine theta   Cos theta   0   0
0 0 1 0
0 0 0 1
 
So the solution is:
0.9999 -0.00767   0  0
0.00767   0.9999   0   0
0 0 1 0
0 0 0 1

**Comment by Mohamed-Alguhiem** [comment]
Answering: Create a matrix to scale a point 3.75 along the x-axis and 4.10 along the y-axis and 4.08 along the z-axis

This is easy:
You only need to memorize the identity matrix for rotation.

Solving:

Step 1: Read the question carefully and know what You are supposed to do (Scale,Rotate,Translate etc..) In this case, we are scaling.

Step 2 identify your points: x=3.75   y=4.10  z=4.08 

Step 3: plug points to the identity matrix that you must memorize for the exam.

Now plug these values into the identity Matrix:

The identity matrix is:
Sx 0 0 0 
0 Sy 0 0 
0 0 Sz 0 
0 0 0 1

So the final solution is:
3.75 0 0 0 
0 4.10 0 0 
0 0 4.08 0 
0 0 0 1

**Comment by DenisBarabanov** [comment]
Create a matrix to rotate a point 0.46 radians around the z-axis. (SAME QUESTION FROM REVIEW)
her answer sheet has
0.9  -0.44 0.0 0.0
0.44 0.9 0 0
0.0 0 1 0
0.0 0 0 1

following ur steps i get something else

**Comment by Mohamed-Alguhiem** [comment]
is that the complete question? What is the question number on the review sheet? Maybe you have to do more stuff to it such as scaling or translating.

**Comment by JessiicaWu** [comment]
Cos(0.46) = 0.9 -sin(0.46)=-0.44 

Rotation around z axis = [cos(delta) -sin(delta) 0 0]
      forumlar                      [sin(delta) cos(delta)]
                                          [0 0 1 0]
                                          [0 0 0 1]

Matrix = [0.9 -0.44 0 0]
               [0.44 0.9 0 0]
               [0 0 1 0]
               [0 0 0 1]

For this, you do not need to use the inverse of cos, but do remember to put on radian mode.

**Comment by DenisBarabanov** [comment]
ok i got those 2, thank u very much =0) ur more helpful then YT
im looking at transformation review sheet she posted. Question number 2 
Create a Matrix to transform the green triangle into the yellow triangle...

**Comment by Mohamed-Alguhiem** [comment]
do it from end to beginning. scale then rotate.

Step 1:
Start with scaling: from the previous question.
The identity matrix is:
Sx 0 0 0
0 Sy 0 0
0 0 Sz 0
0 0 0 1

So scaling solution is:
4.05 0 0 0
0 4.66 0 0
0 0 1.65 0
0 0 0 1
_______________________________________________
Step 2 rotate  1.41 radians.
The identity matrix is:
[cos(delta) -sin(delta) 0 0]
[sin(delta) cos(delta)]
[0 0 1 0]
[0 0 0 1]

So rotating matrix solution is:
[0.160 -0.987  0 0]
[0.987 0.160 0 0]
[0 0 1 0]
[0 0 0 1]
_______________________________________________
step 3: Multiply scaling matrix with rotation matrix

4.05 0 0 0            [0.160 -0.987  0 0]           [0.65 4.0 0.0 0.0]
0 4.66 0 0      *    [0.987 0.160 0 0]       =    [4.6 0.75 0.0 0.0]
0 0 1.65 0             [0 0 1 0]                            [0.0 0.0 1.65 0.0]
0 0 0 1                   [0 0 0 1]                            [0.0 0.0 0.0 1.0]


NOTE: If you don't know how to multiply 4x4 matrix look at this video
https://www.youtube.com/watch?v=sYlOjyPyX3g

**Comment by DenisBarabanov** [comment]
thank u for helping us (theres few of us here)
for question 9 on review sheet is this correct answer
Create a matrix to translate a point -5 in the x direction and 3 in the y direction and -1 in the z direction
[-5 0 0 0] * [x] = -5x
[ 0 3 0 0] * [y] = 3y
[0 0 -1 0] * [z] = -1z
[0 0 0  1] * [1] = 1

did we do it correctly?

**Comment by JessiicaWu** [comment]
Just this
[-5 0 0 0] 
[ 0 3 0 0] 
[0 0 -1 0] 
[0 0 0 1]

**Comment by Mohamed-Alguhiem** [comment]
You need to memorize the identity matrix.

Whenever you see the word translation you just think about the last column.

The Identity matrix is:
1 0 0 tx
0 1 0 ty
0 0 1 tz
0 0 0 1

so  you are told that x= -5  y=3  z=-1 

just replace them with the last column values 

so the answer is 
1 0 0 -5
0 1 0 3
0 0 1 -1
0 0 0 1

**Comment by DenisBarabanov** [comment]
ohhh that part, ok got confused in the slides, thank you

**Comment by DenisBarabanov** [comment]
Hey another questions was asked in the other section 
https://github.com/cisc3620/review/issues/18
4. Create a matrix to translate a point 3 in the x direction and -1 in the y direction and 3 in the z direction, and then scale a point 3.51 along the y-axis, and then rotate a point 1,29 radians around the z-axis.

Matrix to Translate
1) 1 0 0  3
    0 1 0 -1
    0 0 1 3
   0 0 0 1

2) Rotation 
cos(1.29)   -sin(1.29)   0  0
sin(1.29)    cost(1.29)  0  0
0 0 1 0
0 0 0 1
=
0.27  -0.96  0  0
0.96   0.27  0  0
0 0 1 0
0 0 0 1

now i get confused on the scale a point 3.51 along the y axis

is it
1 3.51 0  3
0 1 0 -1
0 0 1 3
0 0 0 1
and then 
do i multiply this matrix by the rotation matrix?

**Comment by Mohamed-Alguhiem** [comment]
I solved it for you over there a while ago check it out.

**Comment by DenisBarabanov** [comment]
thank u, can u check number 5, something is wrong lol

**Comment by Mohamed-Alguhiem** [comment]
you are making mistake with the translate matrix. Also make sure when you are doing rotation you use radians.

the multiplication is as follow:

Rotation * scale

then 

Result * Translate
