### ISSUE TITLE
Viewing question 

### ISSUE THREAD

**Issue by Mohamed-Alguhiem** [cisc3620/review#16]
Does anyone know how to solve this question?
Project point [-4 -1 -3 1] onto the plane n=4.
a) What will px, py, pw be after the perspective transformation is applied? (before the scaling
and translation of the orthographic transformation)
b) What will px, py be after perspective division?

**Comment by JessiicaWu** [comment]
multiple x y with the n plane
so a.) [-16 -4 -3]
-4 x 4 = -16
-1 x 4 = -4
your z becomes w, she said keep it the same so, it will be -3

Then b.) -4 -1
divide x y with the n-plane where n = 4
-16/4 = -4 
-4/4 = -1

**Comment by Mohamed-Alguhiem** [comment]
but the answer for  b is [ 5.33333333 1.33333333] so how do I get that???

**Comment by JessiicaWu** [comment]
I just update my answer, you should divide with w, sorry about that.

**Comment by Mohamed-Alguhiem** [comment]
cool thanks for the fast reply
