### ISSUE TITLE
viewing question number 12

### ISSUE THREAD

**Issue by Mohamed-Alguhiem** [cisc3620/review#17]
So for this question. I follow the same formula in the slide but then i have a problem with the part that says: (2/(f-n))   and - [(f+n) / (f-n)]

 f = 0
n = 1

so (2/(f-n)) is (2/(0-1)) = -2    she got 2 as the answer in the review !!!!!

- [(f+n) / (f-n)] = - [(0+1) / (0-1)]   = - [1 / -1] =  - [-1]  = 1    she got -1 as the answer instead of 1

I am just confused here can someone explain what is going on.
Thanks

@rivlev

**Comment by dancohengtr** [comment]
I have a slight feeling like the generated answers for some of the review questions are incorrect. For example, in the transformations review there are multiple instances of the same exact "create a matrix to transform the green triangle to the yellow triangle." They're all literally the same exact question with the same coordinates and the answers that were generated for them are all completely different.

**Comment by rivlev** [comment]
Unfortunately slide 21 in the viewing slides is an error, I took the image from the book (RTR) and it looks like they just have it wrong there. The following slides (22-23) have the correct ortho matrix with 2/(n-f) (since in a right handed coordinate system n is greater than f, just as r is greater than l and t than b) and that is how we went through it in class. 2/(n-f) = 2/(1-0) = 2.

I encourage you to look into the code to see how the answers were generated when you find something confusing.

**Comment by rivlev** [comment]
@dancohengtr can you give an example?

**Comment by dancohengtr** [comment]
Questions 2, 6, and 10 are all exactly the same question but they all have different answers.

 I'm also having trouble trying to figure out what order to multiply some of the scale, then rotate, then translate or any other combination of the 3, type of questions. I understand that the general order you'd want to do is to first scale, then rotate, then translate. I've tried that method for numbers 4 and 5 have gotten answers that have some of the same numbers as the answers on the answer sheet but the positions in the matrix are slightly different or there are some numbers I'm missing. 

I've done the work in a matrix calculator as well to make sure i'm not making a mistake doing it by hand and some combinations of multiplying the scale, rotate and translate will give me the right answer. Those combinations don't always resemble the TRS method though.

**Comment by rivlev** [comment]
Thanks, I will take a look at those.

To answer the "combo" questions, follow the order *given*, not the "good" order of TRSP. e.g. rotate by d and scale by sx sy -- multiply scale matrix times rotate matrix, not the other way around, even though RS is the "good" order.

**Comment by rivlev** [comment]
Something went wrong in the generation process and all image questions use exactly the same image. Thanks for pointing it out.

**Comment by dancohengtr** [comment]
Thank you I will try that, and yeah it seemed like something funky was going on.

**Comment by Mohamed-Alguhiem** [comment]
Thanks.
