### ISSUE TITLE
Lighting Review: Question 2; Transformation Review: Question 2 Help

### ISSUE THREAD

**Issue by hd1080p** [cisc3620/review#19]
Good Evening,

I am having a bit of trouble seeing why the answer for question 2 in the lighting review is: [0.0 0.0 0.4]

Here is my process:
The equation that has to be used here is ```c = (c_r)(c_l)max(0, n • l)```
where ```c_r = [0.0 1.0 0.5]
              c_l = [1.0 0.0 1.0]
              n   = [.22 .44 .87]
              l    = [.48 .77 .42]```

I calculated ```n • l = .8098 ~ .81```

I became lost after that, forgetting what to do with ```c_r and c_l``` so I tried cross multiplying and then multiplying by the ```max(0, n • l)``` which in turn resulted in the wrong answer. 

---
In the Transformation review, I also had an issue with creating a matrix that transformed the green triangle into the yellow triangle.

![image](https://cloud.githubusercontent.com/assets/16688677/23978922/e5395aea-09cc-11e7-80e2-49603c16bb46.png)

Here is the picture just for reference.

So my process in problem 2 was first try to identify intuitively what this transformation looks like. At first glance it is noticeable that the yellow triangle rotated so I setup a rotation matrix being:
cosΘ -sinΘ 0 &nbsp;0
sinΘ &nbsp;&nbsp;cosΘ 0 0
0 0 1 0
0 0 0 1

Now the confusing part for me here was deciding how to calculate Θ; My process was that I choose one of the points on the yellow triangle ```(-1.29, 0.57)``` for example and with knowing the x and y values I decided to try and find the angle Θ by drawing a right triangle. By knowing x and y (i.e. the adjacent and opposite sides in the right triangle) I did  tan<sup>-1</sup>(0.57/-1.29) which resulted in -0.42. 

I tried plugging the newly found ```Θ = -0.42 rad``` into the rotation matrix and it did not match the answer being:
0.79 -0.61 0.0 0.0
0.61 0.79 0.0 0.0
0.0 0.0 1.0 0.0
0.0 0.0 0.0 1.0

I would just like a nudge in the right direction to understand the problem.

@rivlev 

Thank you!

**Comment by Mohamed-Alguhiem** [comment]
![img_2619](https://cloud.githubusercontent.com/assets/25488160/23979828/5184c806-09d2-11e7-9c3d-be3aa59525d5.JPG)

For Your other question. she mentioned in the hangout review that she will give something simple so i didn't really bother wasting time on those pictures. She showed us a picture of just scaling triangle on the hangout call and said that she will give something simple like that because the one that you are doing involves a lot of algebra.

**Comment by hd1080p** [comment]
I appreciate the help  @Mohamed-Alguhiem
