### ISSUE TITLE
Lighting Review

### ISSUE THREAD

**Issue by destroyer3b** [cisc3620/review#20]
Given a point location of[3.0 −2.0 −4.0]and a light location of[0.0 2.0 1.0], what is the light direction? (Remember to normalize.)

Can someone show me the steps in doing this problem. Thanks.

**Comment by Mohamed-Alguhiem** [comment]
![img_0876](https://cloud.githubusercontent.com/assets/25488160/23980370/9adb8500-09d5-11e7-89e0-dce80c0dda54.JPG)

**Comment by destroyer3b** [comment]
Thanks for the steps!
