### ISSUE TITLE
Ray casting review

### ISSUE THREAD

**Issue by trmchale1** [cisc3620/review#22]
When entering an answer like 0 0 0 (for v1 v2 v3)
Response is 
Incorrect
Correct answer: 
[0.0, 0.0, 0.0]

For 1 1 1
Incorrect
Correct answer: 
[1.0, 1.0, 1.0]

Regardless of the actual correct answer.

**Comment by rivlev** [comment]
I can't reproduce this error, can you give more details?

![screen shot 2017-04-08 at 10 50 09 pm](https://cloud.githubusercontent.com/assets/5970324/24834255/c8e09cc0-1cad-11e7-8723-1bc4099d1adf.png)

**Comment by trmchale1** [comment]
Hi Professor,

python raytracing_review.py
'r' for ray casting

Enter answer in the form v0 v1 v2
0 0 0
Incorrect
Correct answer: 
[0.0, 0.0, 0.0]
direction:
Enter answer in the form v0 v1 v2
1 1 1
Incorrect
Correct answer: 
[1.0, 1.0, 1.0]
