### ISSUE TITLE
Computing Origin and View raytracing

### ISSUE THREAD

**Issue by trmchale1** [cisc3620/review#24]
Given the first question from raytracing as an example:
Asks for origin and view in an orthographic view. View ray is simple just negate w.

To find the origin, the below formula given on slide 9 of raytracing:

e + Uu+ Vv
u = l +(r-l)(i+.5)/x(pixels)
v = b + (t-b)(j+.5)/y(pixels)

-.005 = (-5)+(-4--5)(1+.5)/724
.04 = (0)+(0+4)(3+.5)/344

[-.004,-.002,.002] = [.82,.41,-.41] * -.005
[0,.-.03,-.03] = [0,-.71,-.71] * .04

If our original formula was origin = e + Uu + Vv  
and the formula now looks like origin = e + [-.004-.002,.002] + [0,-.03,-.03]
Our answer is eventually [-6.08,.93,1.01], how can this be?

u and v are insignificantly small and e must must be larger by comparison.

Do we get e by subtracting the pixel value from the ray direction? 

Not sure how to resolve for problems like this.

**Comment by rivlev** [comment]
-.005 = (-5)+(-4--5)(1+.5)/724
is incorrect
it is approximately -5
See https://github.com/cisc3620/review/blob/master/Ray%20tracing%20review.ipynb

**Comment by MutHamed** [comment]
@rivlev 

I'm having a similar issue with the formula

origin = e + uc*u + vc*v

I'm trying to see if I can get the final result ( [-6.0983011  0.9219541  1.0202552] )in the review script, but it seems my calculations are off. For uc*u and vc*v do you multiply the result you get from u = l +(r-l)(i+.5)/x(nx) by u, and similarly for vc*v?

**Comment by rivlev** [comment]
Yes
get uc and vc from i,j, nx,ny, l, r, b, t
u and v are the camera axes given in the question
scale uc by u and uv by v

**Comment by MutHamed** [comment]
@rivlev 

Okay. Thank you so much.
