### ISSUE TITLE
Trouble With Intersection Point Location

### ISSUE THREAD

**Issue by MichaelGregg** [cisc3620/review#27]
@rivlev Could you please clearly explain how to determine if the intersection point is inside the polygon and if the intersection point is in front of viewpoint e? I was not able to intuit how to do it from the answers in the notebook file

**Comment by JessiicaWu** [comment]
Example from her review:
P= e + t*d --your answer of P = [ -5.645 (x intersection)]
Compare this value with the value you get after plugging into the implicit equation of line ->
(y0 − y1)x + (x1 − x0)y + x0y1 − x1y0 = 0
solve for x
Compare this x value with your P x intersection(ex: -5.645)

ex: if x = -5.7797  px=-5.645
Is -5.7797 > -5.645, in this case, its actually smaller than px, so its outside.

if x = -2.87 and px = -5.645
then -2.87 > -5.645, x is greater than px, so it's inside the polygon

TO KNOW IF THE INTERSECTION is in front of viewpoint e:
if t > 0, its in front of the viewpoint. If it's negative, its behind the viewpoint.

I'm not sure if this is confusing to you.

**Comment by rivlev** [comment]
The intersection point is in front of the viewpoint if t > 0

For every **edge** in the polygon (every consecutive pair of vertices, *including the last-first*)
* check if they are on opposite sides of the intersection point in the y direction (if one's y value is greater than the intersection point px, and one's is less). 
   * if not, continue to the next edge
* check if they are both "to the right" of px -- if they both have x coordinates greater than px
   * if both are "to the left", continue to the next edge
   * if both are on the "right", add 1 to the intersection count
   * if they are on opposite sides of px, check whether the x intersection is greater than px
      * Find the equation of the edge. Let's call the two vertices of the edge _f_ and _g_
         * Ax + By + C = 0
         * A = y_a - y_b, B = x_b - x_a, C = x_a * y_b - x_b * y_a (this equation will be given )
         * x = (-B * y_intersectionpoint - C)/A
         * if x > x_intersectionpoint, add 1 to the intersection count
* If the intersection count is odd, the point is inside the polygon.

**Comment by MichaelGregg** [comment]
@rivlev thanks.  To find the T-int of R and P, When dividing (P1-e)•N by D•N, is the answer [A1/B1  A2/B2  A3/B3]   ?

Also, for the X Y and Z on R at T, the formula is e+td.  Is that td t dot (•) d, or t cross(*) d?

**Comment by MichaelGregg** [comment]
@rivlev Also, in response to your explanation about how to tell if the int is inside the polygon, what is px?  For example, you say- check  "if one's y value is greater than the intersection point px, and one's is less".  is px the x value of the vertex calculated in step D (X, Y and Z int on R at T)?

**Comment by JessiicaWu** [comment]
For x,y,z interection forumla:
p = e + t *d (its t times d not crossproduct)

**Comment by MichaelGregg** [comment]
@rivlev Two more questions- 1.) I can not intuit how to compute the barycentric coordinates, could you explain how to do so, in terms of P0, P1, P2, e, d and n? 
2.) Can you explain how to answer the questions asking for the A, B and C components of a line passing through two points where Ax + By + C = 0    ?

**Comment by MichaelGregg** [comment]
@rivlev Next question. (Sorry about all the questions).  Im now referring to the texture mapping slides- 
![screen shot 2017-05-20 at 9 11 07 pm](https://cloud.githubusercontent.com/assets/25493211/26280419/ec214734-3da0-11e7-8258-8b70e73ec569.png) How do i calculate t(4,13)? for what operation does t stand?

**Comment by rivlev** [comment]
t is a scalar, and dot products give a scalar. (p1-e) dot n gives a scalar (not a vector), and so does d dot n, so the numerator and denominator are a single scalar not a vector.

**Comment by rivlev** [comment]
t(4,13) in the texture mapping questions refers to the texture value retrieved from those coordinates. It is the equivalent of e.g. s+t+1 in ray tracing question 7

**Comment by rivlev** [comment]
Ax + By + C
this equation will be given on the final so these kinds of questions will not be asked
it refers to the line equation
(y0-y1)x + (x1-x0)y + x0y1 - x1y0
where A = y0-y1, B=x1-x0, C=x0y1 - x1y0

**Comment by rivlev** [comment]
A barycentric coordinate question is traced in full in Ray tracing review.ipynb, please be more specific about which part you don't understand.

**Comment by MichaelGregg** [comment]
@rivlev Thanks.  You meant texture mapping number 7, right?- 
![screen shot 2017-05-20 at 9 11 07 pm](https://cloud.githubusercontent.com/assets/25493211/26280556/07148f6e-3da7-11e7-9a02-f6dbf804d66f.png)
That is the one i am trying to figure out.  I am trying to figure out b in the bilinear interpolation example slide- 
![screen shot 2017-05-20 at 9 58 03 pm](https://cloud.githubusercontent.com/assets/25493211/26280573/7ae38594-3da7-11e7-8cc9-9f8d27ac21e5.png)
 ...which i need to know how to do to be able to do texture mapping number 7.  I understand all the terms used to calculate b, except for what t does in the t(l, b), t(r, b), etc... What i am asking is how i calculate the texture value from two coordinates?

**Comment by MichaelGregg** [comment]
@rivlev And in terms of the Barycentric coordinates question, in ray tracing review.pynb, i do not understand what is happening in this step: 
![screen shot 2017-05-20 at 10 08 37 pm](https://cloud.githubusercontent.com/assets/25493211/26280608/ee7e27f6-3da8-11e7-99e0-7c683a74b059.png)
Can you explain to me in math terms, the series of calculations needed to compute the beta and gamma values, using the given information (the arrays t, e and d) and the information arrived at through calculations (the normal, t and px)?  What do i do with t.array, e.array, d.array, n, t and px to arrive at beta and gamma?

**Comment by MichaelGregg** [comment]
@rivlev Also, in response to your explanation about how to tell if the int is inside the polygon, what is px? For example, you say- check "if one's y value is greater than the intersection point px, and one's is less". is px the x value of the vertex calculated in step D (X, Y and Z int on R at T)?

**Comment by rivlev** [comment]
re texture mapping: That is given in the question
> the value at each (s, t) texture location is (s+t+1)/1
(s and t are the texture coordinates)

**Comment by rivlev** [comment]
triangle intersection:
1. use e, t, d, p0, n to find an intersection point exactly as in polygon intersection
2. see #30 for barycentric calculation trace

**Comment by rivlev** [comment]
px is the intersection point; compare the vertex y coordinates to its y coordinate (see if they are above or below)

**Comment by MichaelGregg** [comment]
@rivlev so is px equal to (P1-e)•n/d•n   ?

**Comment by rivlev** [comment]
t = (P1-e)•n/d•n 
px = e + t*d

**Comment by MichaelGregg** [comment]
@rivlev thanks

**Comment by MichaelGregg** [comment]
So does f(np.floor(ps), np.floor(pt)) equal (np.floor(ps)+ np.floor(pt)+1)/1    ?

**Comment by rivlev** [comment]
yes
