### ISSUE TITLE
Review Material question

### ISSUE THREAD

**Issue by MichaelGregg** [cisc3620/review#28]
@rivlev You mentioned in class that all we need to study is the post-midterm material.  According to the schedule on the class website, does this mean that if i feel confident with all the questions on the ray_tracing_review, ray_tracing_review.perspective_and_polygon, and the texture review then i will have studied for all the material on the final? Or should i look at the transparency and transformation material too?  I am just trying to figure what i should spend the most time on.

**Comment by rivlev** [comment]
The post-midterm topics are:
* Ray tracing
   * generated_reviews/ray_tracing_review.perspective_and_polygon.pdf (for perspective ray casting and polygon intersection questions) (with an answers file in the same directory)
   * generated_reviews/ray_tracing_review.pdf (with an answers file in the same directory)
   * raytracing_review.py (to interactively generate and check ray tracing questions)
   * Ray tracing review.ipnyb (to see how to trace through ray tracing questions)
* Texture mapping
   * generated_reviews/texture_review.pdf (with an answers file in the same directory)
   * generated_reviews/texture_review.qualitative.pdf 
   * texture_review.py
   * TextureMapping.ipynb
* Transparency
   * generated_reviews/transparency_review.pdf (with answers file in same directory)
* Sample operations
   * generated_reviews/sample_review.pdf (with answers file in same directory)

**Comment by DenisBarabanov** [comment]
Hi Professor
i herd that there is problem with these files, thee is also a red please read note that says that there are errors. Do we need to study these questions even though they are wrong?

generated_reviews/ray_tracing_review.pdf (with an answers file in the same directory)
raytracing_review.py (to interactively generate and check ray tracing questions)
Ray tracing review.ipnyb (to see how to trace through ray tracing questions)

**Comment by AlexLoyko** [comment]
@DenisBarabanov

Look at the ray_tracing prospective and instersection pdfs. Those address the questions that were wrong in the general ray_tracing review pdf

**Comment by DenisBarabanov** [comment]
Hi, 
@AlexLoyko 
ray_tracing_review.perspective_and_polygon.pdf
are you talking about that file? there 2 questions there that keep repeating...do i just need to solve them or also need the broken file?

**Comment by AlexLoyko** [comment]
@DenisBarabanov

You need to solvequestions from both, but from the broken one skip the 2 types of questions that appear on the perspective and intersection ones.

Yep, that file.
