### ISSUE TITLE
Ray Tracing Review Questions and Solutions with Steps

### ISSUE THREAD

**Issue by Mohamed-Alguhiem** [cisc3620/review#32]
Question Number 1)
1. Ray R has starting point e= [-10.43  -6.01   -2.83]  and direction d= [-0.56    0.37     -0.74] Polygon P has vertices: 
[   -5.4      -5.8        -7.4    ]                        Lets call this: p0
[-4.75     0.75       -9.36  ]                        Lets call this: p1
[  -3.22    -3.18      -4.35  ]                        Lets call this: p2
[ -5.84     -7.11       -7.62   ]                       Lets call this: p3
[ -5.18     -2.75      -8.49  ]                        Lets call this: p4

a) Note: There was no a question on the pdf file.

b) What is the normal to P?
c) What is the t intersection point of R and P?
d) What is the (x, y, z) intersection point on R at t?
e) Is the intersection point inside the polygon?
f) Is the intersection point in front of the viewpoint e?
_____________________________________ _____________________________________
Solution:
b) What is the normal to P?
Note: We have to pick a vector and subtract the previous vector from it twice for example: I choose p0,p1 and p2. so i will do p[1]-p[0]  ,  p[2]-p[1]. You can choose any vectors you want.

STEP 1: p[1]-p[0]  ,   p[2]-p[1]   = [  -4.75     0.75       -9.36  ]  -   [   -5.4      -5.8        -7.4     ] 
                                                        ,[  -3.22    -3.18      -4.35  ]   -   [  -4.75     0.75       -9.36  ]
                                                 
                                                    = [   0.65     6.55      -1.96   ] ,      
                                                        [  1.53      -3.93        5.01   ]

STEP 2: Cross Product:
We have to take the cross product of the two vectors we just got. cross(p[1]-p[0]  ,  p[2]-p[1])
Note: If you forgot how to do cross product look at this video: 
https://www.youtube.com/watch?v=qsgK1d-_8ik&t=310s

[   0.65     6.55      -1.96   ]   x   [  1.53      -3.93        5.01   ]
=          (6.55 * 5.01)  - (-3.93 * -1.96) i   =   25.1127
  (-1) * (0.65 * 5.01)   - ( 1.53 * -1.96)  j   =  -6.2553 
            (0.65 * -3.93) - (1.53  *  6.55) k   =  -12.576
So after taking the cross product this is our new vector:
               [  25.1127  -6.2553    -12.576  ]

STEP 3: normalize:
We have to normalize the vector we got from taking the cross product in the previous step:
normalize(cross(p[1]-p[0]  ,  p[2]-p[1]))

To Normalize a vector we have to squre every elemet then add them and then take the square root of the solution:
squareRoot(   25.1127^2  +  -6.2553^2   +  -12.576^2  )  = 28.7738
                   [   (25.1127/28.7738)       (-6.2553/28.7738   ( -12.576/28.7738)  ]

                  Normal of P soultion  =   [ 0.8727   -0.21739   -0.43706 ]
                  Round to 2 dec place: =  [ 0.87   -0.22   -0.44 ]

c) What is the t intersection point of R and P?

Solution for C:
Step 1:  I dentify the elements and formula.
             Formula to get the t intersection:         t = (p0 -e) .dot(normal)/ d . dot (normal)
             p0         =    [   -5.4      -5.8      -7.4  ]    GIVEN
             e            =    [  -10.43   -6.01   -2.83 ]   GIVEN
             normal  =    [   0.87     -0.22    -0.44 ]   Solution From Part B
             direction=   [ -0.56     0.37     -0.74  ]   GIVEN

Step 2: Solve (p0 -e)
           [   -5.4      -5.8      -7.4  ] -   [  -10.43   -6.01   -2.83 ]  = [5.03   0.21  -4.57]

Step 3: Take the dot product of (p0 -e) and the normal vector
 t = (p0 -e) .dot(normal)/ d . dot (normal)
             (p0 -e) DOT normal = [5.03   0.21  -4.57  ]   DOT   [   0.87     -0.22    -0.44 ] 
                                               =  [  (5.03* 0.87) + (0.21*-0.22) + (-4.57*-0.44)  ]
                                               =  6.3407
             (p0 -e) .dot(normal)/ d =  6.3407 / [ -0.56     0.37     -0.74  ] 
                                                    = -11.3226   17.137  -8.5685

             t = (p0 -e) .dot(normal)/ d . dot (normal) 
                 = [-11.3226   17.137  -8.5685] DOT [0.87 -0.22 -0.44 ]
                                                     
      
Step 4: Take the dot product of the direction d vector  and the normal vector
          [-0.56    0.37     -0.74]    DOT    [   0.87     -0.22    -0.44 ] 
      =  [  (-0.56* 0.87) + (0.37*-0.22) + (-0.74*-0.44)  ]
      = -0.243

Step 5:  Divide Solutions from Step 3 by Solution from Step 4:
         6.3407 / -0.243 
        = -26.0934      I think the answer on the PDF is wrong for this or it used p1 instead of P0 check the    
                                  image for Jupyter problem with steps. To vertify that the steps are correct.

d) What is the (x, y, z) intersection point on R at t?
           check the image problem to see the steps for this problem
e) Is the intersection point inside the polygon?
           check the image problem to see the steps for this problem
           Inside = odd
           outside = even
           0 never touch

f) Is the intersection point in front of the viewpoint e?
# If endpoints of edge are above and bel
# Ax + By + C = 0
# (y0-y1)x + (x1-x0)y + x0y1 - x1y0 = 0 (Given)
# equation of edge 01

           check the image problem to see the steps for this problem
           if solution is > x    then its inrfront of the view point.

Note: I will upload the remaining problems with the texture problems tomorrow.

![1](https://cloud.githubusercontent.com/assets/25488160/26294078/380c254e-3e8f-11e7-9411-269c1539767d.JPG)

![2](https://cloud.githubusercontent.com/assets/25488160/26294083/3e24880e-3e8f-11e7-90a1-1db381ae41b0.JPG)

![3](https://cloud.githubusercontent.com/assets/25488160/26294090/41ce2adc-3e8f-11e7-812b-894a78b9ff24.JPG)

![4](https://cloud.githubusercontent.com/assets/25488160/26294091/44fda8ea-3e8f-11e7-8199-dd0e71f98b06.JPG)

![5](https://cloud.githubusercontent.com/assets/25488160/26320598/55effc04-3ef1-11e7-82d6-7c95a2c96650.JPG)

![7](https://cloud.githubusercontent.com/assets/25488160/26323939/bc1de31c-3efe-11e7-8adf-6a18e19073e2.JPG)

![6](https://cloud.githubusercontent.com/assets/25488160/26323935/b73da562-3efe-11e7-82ca-df2857bddc4b.JPG)

![8](https://cloud.githubusercontent.com/assets/25488160/26325869/ad07fc66-3f06-11e7-857f-6d28df4e085a.JPG)

Question 7) Ray_Tracing_Review: barycentric coordinates.
![9](https://cloud.githubusercontent.com/assets/25488160/26339775/62a96432-3f58-11e7-8890-5125d8a9a1fa.JPG)

![10](https://cloud.githubusercontent.com/assets/25488160/26339779/65c81366-3f58-11e7-92ef-b209c4bc211b.JPG)

![11](https://cloud.githubusercontent.com/assets/25488160/26339782/68b5bee8-3f58-11e7-934d-33cb03239e3f.JPG)

Question 7) Ray_Tracing_Review: Origin and Direction: Orthographic view point.

![12](https://cloud.githubusercontent.com/assets/25488160/26342723/2d7f55b4-3f67-11e7-8876-a0345db1e0fc.JPG)

![13](https://cloud.githubusercontent.com/assets/25488160/26342738/37272f06-3f67-11e7-8e03-f5dd90445586.JPG)

**Comment by DenisBarabanov** [comment]
Jesus, how can we do this one during the final and have time left...im not ALBERT EINSTEIN lol

**Comment by Mohamed-Alguhiem** [comment]
Good Luck
