### ISSUE TITLE
#6 Ray-Tracing 

### ISSUE THREAD

**Issue by Natia94** [cisc3620/review#34]
what are the A, B, C components of the line passing through [-3, 2, 3] and [-2,-4, -5] when ax^2+bx+c=0?
Professor, how can I solve this problem? Do I need to use this formula-(y0-y1)x + (x1-x0)y + x0y1 - x1y0 and if yes, how can I use it? y0, y1.... confuses me. Thanks!
@rivlev

**Comment by Mohamed-Alguhiem** [comment]
![8](https://cloud.githubusercontent.com/assets/25488160/26325910/e09352c4-3f06-11e7-9992-e1421676785f.JPG)

**Comment by Natia94** [comment]
Thanks! makes sense now. 
suppose a texture is applied to an area of size 116x116. a) what two levels of details (powers of two) should be used for trilinear interpolation? b) how should each one be weighted?
@Mohamed-Alguhiem can u help me with this problem too?

**Comment by Natia94** [comment]
how we can get 64 and 128? 0.19 and 0.81?

**Comment by Mohamed-Alguhiem** [comment]
b) 64 and 128      :This is common sense because 116 is between resloutions 64 and 128. If 116 was lets say 189 it would be between 128 and 256

c) 116 -64/128-64 = 0.81

The weight of 64 = 1 - 0.81 = 0.19
The weight of 128 =  1- 0.19 =  0.81

**Comment by Natia94** [comment]
@Mohamed-Alguhiem got it! thanks

**Comment by AlexLoyko** [comment]
Guys...
What time is our final and where? Thanks in advance

**Comment by Natia94** [comment]
same room 10 to 12

**Comment by Mohamed-Alguhiem** [comment]
10:30-12:30 
SAME ROOM 
TOMOROW

**Comment by AlexLoyko** [comment]
Thanks!

**Comment by DenisBarabanov** [comment]
@AlexLoyko 
We are going to show up at around 9 30 for additional review if u want to join us

**Comment by AlexLoyko** [comment]
@DenisBarabanov

Sure. Ill join

**Comment by DenisBarabanov** [comment]
I think me and Mohmed gave up on sleeping...lol =P he been up for 40hours and i been up for over 20+...lol

**Comment by Mohamed-Alguhiem** [comment]
Do you still need help with any questions
