### ISSUE TITLE
Texture Review Questions and Solutions with Steps

### ISSUE THREAD

**Issue by Mohamed-Alguhiem** [cisc3620/review#35]
Question 1) Texture_Review.pdf 
![14](https://cloud.githubusercontent.com/assets/25488160/26343902/be849886-3f6b-11e7-8fae-31a4a52d8457.JPG)

Question 2) Texture_Review.pdf 
![15](https://cloud.githubusercontent.com/assets/25488160/26348506/ed4f3e0a-3f7a-11e7-9365-04f08d55b82b.JPG)

Question 5) Texture_Review.pdf 
![16](https://cloud.githubusercontent.com/assets/25488160/26348542/05376664-3f7b-11e7-94cd-6a4c73478078.JPG)

Question 6) Texture_Review.pdf 
![17](https://cloud.githubusercontent.com/assets/25488160/26348556/1065dd9a-3f7b-11e7-8d4e-7fd8463b0d76.JPG)

**Comment by yeraymond** [comment]
Thank you for your hard work. I appreciate it.

**Comment by Mohamed-Alguhiem** [comment]
Good Luck
