### ISSUE TITLE
Problem with installing pillow

### ISSUE THREAD

**Issue by JessiicaWu** [cisc3620/review#4]
I tried using pip install Pillow, but it gives me a syntax error, stating it's an invalid syntax.

@rivlev

**Comment by rivlev** [comment]
is this in the bash shell? not interactive Python?

**Comment by JessiicaWu** [comment]
yes in the bash shell.

**Comment by rivlev** [comment]
Were you able to use pip to install other packages (such as numpy)?

Meanwhile you can comment out the statement `from PIL import Image` and functions containing Image to get the rest of the transformations review to work.

**Comment by JessiicaWu** [comment]
Yes I was able to install numpy. Thanks, it work when I comment it out.
