### ISSUE TITLE
pip issue

### ISSUE THREAD

**Issue by MichaelGregg** [cisc3620/review#6]
For macOS Sierra 10.12.3 after running the python installer, when i try to install pip:
![screen shot 2017-03-11 at 3 01 43 pm](https://cloud.githubusercontent.com/assets/25493211/23826524/b141a134-066b-11e7-90ec-e0aa346e8d9d.png)

**Comment by MichaelGregg** [comment]
By the way, i did download the most recent release of Python 3 (3.6)

**Comment by rivlev** [comment]
Can you do it with easy_install?

`sudo easy_install pip`

**Comment by MichaelGregg** [comment]
When i try easy_install:
![screen shot 2017-03-13 at 4 56 43 pm](https://cloud.githubusercontent.com/assets/25493211/23874963/13664b78-080e-11e7-9576-8e3da527c978.png)
I ran the installer on the Python 3.6 and have the Python Launcher open:
![screen shot 2017-03-13 at 4 58 40 pm](https://cloud.githubusercontent.com/assets/25493211/23875034/5b6f525c-080e-11e7-8d1d-1fd0745d1c19.png)
but, for some reason my system is still using a previous release:
![screen shot 2017-03-13 at 4 59 36 pm](https://cloud.githubusercontent.com/assets/25493211/23875068/79eb1180-080e-11e7-8529-8a0526f14045.png)
Is there an additional step i need to do after running the installer in order to be able to execute the pip commands in the instructions?

**Comment by rivlev** [comment]
you have a typo in your command `easy_intall` instead of `easy_install`

Use the command python3 instead of python to use python 3. (and pip3 instead of pip)

**Comment by MichaelGregg** [comment]
@rivlev Thanks, i am now at the point where i have completed the step of choosing the number for the mirror closest to me:
![screen shot 2017-03-13 at 7 08 09 pm](https://cloud.githubusercontent.com/assets/25493211/23878911/7259b5a4-0820-11e7-96af-01da2e744d9a.png)
Underneath that there are about fifteen sections that look like this of which i could fit all into a single screenshot:
![screen shot 2017-03-13 at 7 07 31 pm](https://cloud.githubusercontent.com/assets/25493211/23878934/9212dcfe-0820-11e7-8049-446d59e5d8a8.png)
and underneath those sections i get this message:
![screen shot 2017-03-13 at 7 05 24 pm](https://cloud.githubusercontent.com/assets/25493211/23878951/aa9e2b98-0820-11e7-8fac-62f630ba7158.png)
as you can see, i typed the quit message after.
That was the last step in the instructions, what should i do next to view the review questions?  
I have cloned the URL into a local file;
![screen shot 2017-03-13 at 7 12 18 pm](https://cloud.githubusercontent.com/assets/25493211/23879019/010f8b20-0821-11e7-83a6-c9d9cd252ece.png)
But can not figure out what to do from here in order to view the questions

**Comment by rivlev** [comment]
from the terminal: python3 transformation_review.py

**Comment by rivlev** [comment]
etc.

**Comment by MichaelGregg** [comment]
When i try python3 transformation_review.py:
![screen shot 2017-03-13 at 8 55 31 pm](https://cloud.githubusercontent.com/assets/25493211/23881215/71f9119a-082f-11e7-8bbe-33e1c1a5db98.png)
I thought this might mean i need to execute the install numpy command again:
![screen shot 2017-03-13 at 8 56 37 pm](https://cloud.githubusercontent.com/assets/25493211/23881259/ce7918b6-082f-11e7-96ba-64dc64af371e.png)

**Comment by rivlev** [comment]
numpy is installed for python 2. do pip3 install numpy to get the python 3 version

**Comment by rivlev** [comment]
Please close if this resolves your issue.
