### ISSUE TITLE
Snow closing

### ISSUE THREAD

**Issue by rivlev** [cisc3620/review#8]
Hi all, 

Brooklyn College will be closed tomorrow, Tuesday 3/14, due to snow. Please note that the midterm WILL be held on Thursday 3/16 as scheduled. 

To help you prepare for the exam, I will hold a review on Hangouts in which I will go over review questions. The link is here: https://hangouts.google.com/hangouts/_/vprl5bvi25dxtd5wy32uzkbgeue. The call will start at 11 and end at 12:15 or when all participants have left. The call is optional. If you have questions be sure to join at the beginning of the call, or it may end before you join.

I will also hold office hours before the exam starting at 9:30 in the classroom.

Finally, I will post review questions and answers generated from the review scripts for those who have trouble running the scripts. 

If you have questions regarding any of this, please respond on github only so that everyone can see the discussion. If the hangouts link is not working at 11 tomorrow, please post on github. Email inquiries will not be answered.

R

------------------------------------------------------
Rivka Levitan, Assistant Professor
Dept. of Computer and Information Science
Brooklyn College & CUNY Graduate Center
www.sci.brooklyn.cuny.edu/~levitan

**Comment by MichaelGregg** [comment]
@rivlev Thanks, where and when will the review questions be posted?

**Comment by rivlev** [comment]
On the class website. I'll update here when they're posted (later this evening)

**Comment by rivlev** [comment]
transformation and viewing reviews now posted.

**Comment by rivlev** [comment]
in this repository under generated_reviews

**Comment by rivlev** [comment]
lighting and vector math reviews now posted

**Comment by amenak** [comment]
@rivlev  I accidentally left and wasn't able to join back. I think google hangouts only works with up to ten people. 
![2017-03-14 6](https://cloud.githubusercontent.com/assets/20450978/23909050/0e8fe9a8-08ac-11e7-9756-202fb07efbdb.png)

**Comment by rivlev** [comment]
Thank you, you're right. Did you have more questions?
