### ISSUE TITLE
Correct Answer on review

### ISSUE THREAD

**Issue by AlexLoyko** [cisc3620/review#9]
@rivlev 
Professor, 

I have encountered the following problem: looks like the answer does not match the question. Am I doing something wrong?

<img width="569" alt="screen shot 2017-03-13 at 9 21 35 pm" src="https://cloud.githubusercontent.com/assets/13985766/23881818/51959e1a-0833-11e7-9904-9f3f19f1fac6.png">

**Comment by rivlev** [comment]
You're right, this is incorrect. Are you getting this on more combo questions? I'll try to find the bug.

**Comment by AlexLoyko** [comment]
Yes, I have experienced problems with other questions on the topic. Just missed to take a screenshot.
